### PR TITLE
Handle composite ID

### LINKED ISSUE #194: StackOverflow with composite ID and Auditable
### Steps to Reproduce

Given a domain class that has a composite ID and is `Auditable`

```groovy
class FooBar implements Auditable, Serializable {
    
    Foo foo
    Bar bar

     static mapping = {
          id composite:['foo', 'bar']
     }
}
```

Deleting an instance of such a domain class causes a `StackOverflowException`.

I think the problem is that in this case `ident()` is a `FooBar` again because of the composite ID.

So `getLogEntitityId`calls `convertLoggedPropertyToString("id", <ident() FooBar>)` which calls `<ident() FooBar>.logEntityId` which calls `convertLoggedPropertyToString` ... 

### Environment Information

- **GORM Version:** 6.1.12.RELEASE
- **Grails Version (if using Grails):** 3.3.10
- **Plugin Version:** 3.0.4
- **JDK Version:** 1.8.0.192

### PR DESCRIPTION
**Pull request by felixscheinost**
This handles domains with composite ident's which currently cause a StackOverflowException.

It also contains changes to the build.gradle file 

fixes #194

### CODE REVIEW

File: examples/audit-test/grails-app/domain/test/TestEntity.groovy [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package test
+
+import grails.plugins.orm.auditable.Auditable
+
+@SuppressWarnings("GroovyUnusedDeclaration")
+class TestEntity implements Auditable {
```
Comment (felixscheinost) [inline examples/audit-test/grails-app/domain/test/TestEntity.groovy]: I had to move this class to the domain folder because `getLogId` now always calls the static method  `getGormPersistentEntity` which failed because the class wasn't correctly setup as a `GormEntity`

File: plugin/build.gradle [hunk 2]
```diff
@@ -27,6 +24,7 @@ apply plugin: "org.grails.grails-plugin"
 apply plugin: "org.grails.grails-plugin-publish"
 apply plugin: "org.grails.grails-gsp"
 apply plugin: "org.asciidoctor.convert"
+apply plugin: 'com.jfrog.bintray'
```
Comment (felixscheinost) [inline plugin/build.gradle]: Need to use old plugin syntax otherwise including the project inline in another gradle project fails

File: plugin/build.gradle [hunk 3]
```diff
@@ -11,14 +11,11 @@ buildscript {
...
+        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.4'
     }
 }
 
-plugins {
-    id "com.jfrog.bintray" version "1.4"
-}
-
-version file("$rootDir/version.txt").text.trim()
+version project.file("../version.txt").text.trim()
```
Comment (felixscheinost) [inline plugin/build.gradle]: This way the path is resolved correctly even when included inline in another project.
